_wandb:
    value:
        cli_version: 0.27.0
        e:
            25ylb3ow0pc6a81q4kc3o5p4y348khzv:
                codePath: c:\Users\Joey\Desktop\Cambridge\Work\Thesis\WGPR.ipynb
                codePathLocal: WGPR.ipynb
                email: zyw26@cam.ac.uk
                executable: c:\Users\Joey\Desktop\Cambridge\Work\Thesis\VenvThesis\Scripts\python.exe
                git:
                    commit: 8fc92af3687ceb690ddf7a1c95780a9fe15e2345
                    remote: https://github.com/JoeyWee1/SolarCycleForecasting.git
                host: NCC-ACNH-1701
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\Joey\Desktop\Cambridge\Work\Thesis\WGPR.ipynb
                python: CPython 3.10.11
                root: c:\Users\Joey\Desktop\Cambridge\Work\Thesis
                startedAt: "2026-05-21T11:25:09.996015Z"
                writerId: 25ylb3ow0pc6a81q4kc3o5p4y348khzv
        m: []
        python_version: 3.10.11
        t:
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.11
            "5": 0.27.0
            "8":
                - 1
                - 3
            "12": 0.27.0
            "13": windows-amd64
kernel:
    value: rotation_only
po:
    value:
        - -5.219221030897092
        - 2.3580197998821464
        - 0
        - -4.605170185988091
        - -0.6931471805599453
        - -6.907755278982137
terms:
    value:
        - RotationTerm
